// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Atelier Socle SAS

import Foundation

/// Configuration for HLS segment encryption.
///
/// ## AES-128 (Full Segment Encryption)
///
/// ```swift
/// let config = EncryptionConfig(
///     method: .aes128,
///     keyURL: URL(string: "https://example.com/key.bin")!
/// )
/// ```
///
/// ## Key Rotation
///
/// ```swift
/// let config = EncryptionConfig(
///     method: .aes128,
///     keyURL: URL(string: "https://example.com/key.bin")!,
///     keyRotationInterval: 10
/// )
/// ```
///
/// - SeeAlso: ``SegmentEncryptor``, ``EncryptionMethod``
public struct EncryptionConfig: Sendable, Hashable {

    /// Encryption method.
    public var method: EncryptionMethod

    /// URL where the decryption key is (or will be) hosted.
    ///
    /// This URL is written into the `EXT-X-KEY` tag's `URI` attribute.
    public var keyURL: URL

    /// The actual 16-byte encryption key.
    ///
    /// If `nil`, a random key is generated by ``SegmentEncryptor``.
    public var key: Data?

    /// Explicit initialization vector (16 bytes).
    ///
    /// If `nil`, the IV is derived from the media sequence number
    /// per RFC 8216 Section 5.2.
    public var iv: Data?

    /// Key rotation interval in segments.
    ///
    /// - `nil`: Single key for the entire stream.
    /// - `1`: Per-segment keys (most secure, highest overhead).
    /// - `N`: Rotate key every N segments.
    public var keyRotationInterval: Int?

    /// `KEYFORMAT` attribute value for `EXT-X-KEY`.
    ///
    /// For standard AES-128 this is typically `nil` (defaults to
    /// `"identity"`). For FairPlay:
    /// `"com.apple.streamingkeydelivery"`.
    public var keyFormat: String?

    /// `KEYFORMATVERSIONS` attribute value for `EXT-X-KEY`.
    public var keyFormatVersions: String?

    /// Whether to write the key file alongside segments.
    ///
    /// When `true`, writes `key.bin` to the output directory.
    /// When `false`, assumes the key is hosted externally.
    public var writeKeyFile: Bool

    /// Creates an encryption configuration.
    ///
    /// - Parameters:
    ///   - method: Encryption method (default: `.aes128`).
    ///   - keyURL: URL for the key in the playlist.
    ///   - key: Optional pre-generated 16-byte key.
    ///   - iv: Optional explicit IV.
    ///   - keyRotationInterval: Rotate key every N segments.
    ///   - keyFormat: KEYFORMAT attribute value.
    ///   - keyFormatVersions: KEYFORMATVERSIONS attribute value.
    ///   - writeKeyFile: Write key to output directory.
    public init(
        method: EncryptionMethod = .aes128,
        keyURL: URL,
        key: Data? = nil,
        iv: Data? = nil,
        keyRotationInterval: Int? = nil,
        keyFormat: String? = nil,
        keyFormatVersions: String? = nil,
        writeKeyFile: Bool = true
    ) {
        self.method = method
        self.keyURL = keyURL
        self.key = key
        self.iv = iv
        self.keyRotationInterval = keyRotationInterval
        self.keyFormat = keyFormat
        self.keyFormatVersions = keyFormatVersions
        self.writeKeyFile = writeKeyFile
    }
}
